### ISSUE TITLE
0.12 Release

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1104]
While the [original issues I marked out for the `0.12` milestone](https://github.com/PyO3/pyo3/milestone/4) are still not yet completed, I think that master already contains a lot of changes compared to `0.11.1`.

So I'm tempted to suggest we push most of the outstanding issues from the `0.12` milestone into the `0.13` milestone (unless there is sudden movement on any of them) and start heading towards releasing `0.12`. I think it doesn't really matter if the rest of the proposals don't land until `0.13`.

This is what I still think should probably happen before an `0.12` release (as well as anything else people contribute):
- [x] Write migration guide entry related to the exception changes I landed in #1024 .
- [x] Ideally I'd still like the three tickets related to `PyErr`  to be completed (#592, #682, #1034), given that #1024 laid the groundwork for this to be possible.
- [x] It would be nice to finish off the doc ticket #376
- [x] @kngwyu finishing a fix for #844 
- [ ] `#[pyenum]` #1045
- [x] `#[derive(FromPyObject)]` #1065

Any thoughts?

**Comment by kngwyu** [comment]
I want to include the fix for #844. And we still need to conversion table though we have https://pyo3.rs/v0.11.1/conversions.html?

**Comment by davidhewitt** [comment]
Thanks, I added that to my post. 

For the doc table - yeah I think it's still a good idea. I'll probably open a PR about it over the weekend, and hopefully you'll see then that it's useful.

**Comment by kngwyu** [comment]
In addition, I also want to include some enum-related PRs (#1045 and #1064)

**Comment by davidhewitt** [comment]
👍 it would be good to have #1045 and #1065 (which I think you meant, not #1064), but if our contributors need more time to design these features I wouldn't think we have to wait for these to go in `0.12`.

**Comment by mvaled** [comment]
#844 can be checked.

**Comment by davidhewitt** [comment]
Of the issues still remaining in the list at the top, it's mostly documentation waiting on me (including the `PyErr` PR, which is just waiting for me to add docs and test). I'm moving house in just under two weeks, so I definitely aim to get it all wrapped up ASAP before my life is swarmed by piles of packing boxes!

There's also #1045. @kngwyu / @stillinbeta what's your thoughts on the status of that PR? If you'd like more time on it, I'm thinking that we move it to the `0.13` milestone.

**Comment by davidhewitt** [comment]
If I don't hear any objections, I would like to make the 0.12 release this week. I'll probably merge #1115 on Wednesday evening, and the only other piece we're waiting for is the change to `add_function` discussed in #1156

**Comment by gilescope** [comment]
Friend has one last tweak to add - to help pick up python in anaconda envs. Should be raised soon.
