### ISSUE TITLE
0.14 Release

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1570]
I think the 0.14 release would be worth putting out soon. We've merged a lot of cleanups as well as a couple of new features. Also the updates to the `num` and `hashbrown` dependencies will probably be useful for the downstream crates to have.

This is what I propose we could merge before the 0.14 release goes live:
  - [ ] #1567 and some follow-up PRs to tidy up the attributes like `#[name = "..."]`, `#[text_signature = "..."]` to be a single `#[pyo3(name = "...", text_signature = "...")]`. Also documentation #1432 
  - [x] #1560 - I think we all agree that simplifying `#[pyproto]` can be a good thing
  - [ ] I'd like to write some new notes on "Getting Started" and "Installing Python" to just make the first words in the README and guide just a little easier for new users. (This should close a few of the easy docs issues.)
  - [x] Some PRs which have been waiting for a while, which would be nice to merge. If the original authors have been diverted by other callings I'll finish them off:
    - [x] #1475 
    - [x] #1128
    - [x] #832

**Comment by davidhewitt** [comment]
However, also none of these changes would be breaking, so I could just release 0.14 already?

**Comment by davidhewitt** [comment]
Note: https://github.com/PyO3/pyo3/pull/1626#issuecomment-847644578 - cross-compiling on `main` is temporarily broken thanks to the new `pyo3-build-config` crate - need to fix (or revert) `pyo3-build-config` before any release can happen.

**Comment by davidhewitt** [comment]
@messense @birkenfeld I think we're very close now to a 0.14 release. This is what I still would like to see merged:

- [ ] The cross-compiling fix for #1648 needs to go in
- [ ] #1657 - this has a bugfix that I think is really important (inherited dict memory leak)
- [ ] `#[pymodule(name)]` PR - that's the last change for #1567 / #1601 which I'd like to put into 0.14

The remaining items I suggested in the OP are just documentation and bugfixes, which I think are good candidates to work on immediately after a release anyway.

Anything else you folks think we should include? Would you be willing to review those outstanding PRs? Once they're merged I'll prepare a release branch and propose a date to put it live.

**Comment by davidhewitt** [comment]
The release is now live!
