### ISSUE TITLE
0.19 Release

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#3154]
As discussed in https://github.com/PyO3/pyo3/pull/2593#issuecomment-1548327079 let's put out 0.19 release soon and then make MSRV bump breaking changes to ease the pain with CI.

As usual, list of a few things which I was hoping to round off before the release:
- [x] I'd like to finish #2881, as I've had a few people ask me about performance of instance checking (e.g. #3104) 
- [x] In conversation with @adriangb it was reported that `#[pyclass(extends = PyBaseException)]` doesn't compile without the `unsendable` option, though I haven't investigated this (sounds like a bug).
- [x] I think `PyCell<T>` and `Py<T>` for `#[pyclass(frozen)] struct T` should have a method to access `&T` without needing the GIL. I believe this is safe and will help us make progress to nogil / sub-interpreter support (by encouraging use of frozen pyclasses which can then use Rust synchronization mechanisms).
- [x] ~~I wanted to add `PyNotImplemented`, `PyEllipsis` and `PyNone` singleton types: https://github.com/PyO3/pyo3/pull/2911#discussion_r1087252466~~ Parked for now as #3162, see https://github.com/PyO3/pyo3/issues/3154#issuecomment-1553677796
- [x] I suggested I would implement #3077, although it may be better to postpone this to 0.20 now (sorry!)
- [x] Prevent dropping unsendable classes on other threads #3176
- [x] Avoid acquiring the GIL during `__traverse__` #3168 #3175

**Comment by adamreichold** [comment]
> I think PyCell<T> and Py<T> for #[pyclass(frozen)] struct T should have a method to access &T without needing the GIL. I believe this is safe and will help us make progress to nogil / sub-interpreter support (by encouraging use of frozen pyclasses which can then use Rust synchronization mechanisms).

I think this would require an additional `T: Send + Sync` bound though, wouldn't it? `Py<T>` is unconditionally `Send + Sync` and even a `#[pyclass(frozen)]` could contain types like `Rc` or `RefCell`, couldn't it?

**Comment by adriangb** [comment]
Sorry for giving you so many problems. Let me at least look into the PyBassException thing.

**Comment by davidhewitt** [comment]
> I think this would require an additional T: Send + Sync bound though, wouldn't it? Py<T> is unconditionally Send + Sync and even a #[pyclass(frozen)] could contain types like Rc or RefCell, couldn't it?

Good point. I think `Sync` may be enough to allow `&T` from multiple threads? The drop requirements for `Send` are protected by `unsendable`.

**Comment by davidhewitt** [comment]
> Sorry for giving you so many problems. Let me at least look into the PyBaseException thing.

No problem; I think hopefully that one's not too hard once I see the compiler's full output!

**Comment by davidhewitt** [comment]
For `Ellipsis` / `None` / `NotImplemented` I've decided I'd prefer not rush to add these now, because fixing #1056 might yet adjust our object model and in the meanwhile we can think about their API. I've left #3162 to remember this for later.

**Comment by davidhewitt** [comment]
@datatriny I wonder if we think it's possible to release 0.19 with the new license, or whether the final few contributors will take long enough that we should hope to release that with 0.20?

**Comment by adamreichold** [comment]
@davidhewitt I would like to nominate including #3165 in this release if solution in #3168 turns out to be workable. Otherwise we might have to wait for another chance for a breaking change before fixing this.

If my understanding of the issue is correct, we should also definitely include #3169 to avoid releasing `Py::get` and `PyCell::get` with incorrect trait bounds.

**Comment by DataTriny** [comment]
@davidhewitt I've now contacted everyone and will wait two weeks before sending reminders. We'd be lucky if the relicensing is done before the end of June.

So not ready for 0.19 I guess.

**Comment by adamreichold** [comment]
> If my understanding of the issue is correct, we should also definitely include https://github.com/PyO3/pyo3/pull/3169 to avoid releasing Py::get and PyCell::get with incorrect trait bounds.

So while that one was a dud, I think we should nevertheless include the fix for the unrelated issue #3176 discovered during the discussion.

**Comment by adamreichold** [comment]
I think that if tonight's remaining merge trains land, we are ready to create a 0.19 release before ~~the purge~~ the MSRV bump. 🤪

**Comment by davidhewitt** [comment]
Agreed, I'm happy to cut this tomorrow evening unless you're particularly wanting to do it @adamreichold

**Comment by adamreichold** [comment]
Not particularly, I would like to focus on the follow-up NumPy release (admittedly a smaller endeavour, but it would like follow up in a timely manner).
