### ISSUE TITLE
0.20 release

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#3246]
Debian bookworm was released a week ago now, so we're able to release 0.20 whenever suits us and send the MSRV bump downstream. I don't think there's pressure to release right away, so here's a list of proposal of items I'd hope to ship in this release.

Given the new support for `__eq__` and the discussions around `__next__` / `__anext__`, I think it would be nice thematically to push a group of improvements to protocol methods in 0.20. Namely, I'm aware of possible changes to:

- [ ] `__del__` - #2484 and also a GC bug #3064 which I think both require a rework to our `tp_dealloc`
- [ ] `__next__` and `__anext__` - possible redesign as discussed in #3190
- [x] `#[new]` (i.e. `__new__`) - #2384 
- [ ] `__buffer__` and `__release_buffer__` - #3148

I've ordered these by my own opinion of their priority (which will differ for others). I'd like to aim to implement these in the same order over the next few weeks, and then prepare the release.

If anyone would like to see other items in the release, or to release sooner without these, please comment. Similarly if anyone wants to own the implementation for anything listed here, feel free to stake your claim so that we don't accidentally push over each other 😄 

Other possible items (from discussion below):
- [ ] #3061 
- [x] #3325

**Comment by adamreichold** [comment]
I would like to nominate completing the license change for the 0.20 release.

**Comment by davidhewitt** [comment]
I think that'll be subject to the outcome of #2384

**Comment by orowith2os** [comment]
Also worth mentioning https://github.com/PyO3/pyo3/issues/3268.

**Comment by davidhewitt** [comment]
Some resolution / mitigation for #3325 would be desirable, I'll add to the OP.

**Comment by davidhewitt** [comment]
As the changes for #3325 have the potential for quite a few edge cases which will cause disruption to user code, and we have quite a lot already merged waiting to release, I'm wondering about switching priorities up and just helping get #3325 resolved and then cutting a release.

We also have a plan for the new higher-performance API in #3382 which I think is both quite a lot of work and also likely to yield some great improvements, so I'm quite keen to get on with the 0.21 release cycle.

The rest of the trait changes for `__next__`, `__anext__` etc can land in 0.21 if they're not too breaking, else maybe they're better to land in 0.22 once the dust has settled from the API rework.

Any objections? :)

**Comment by alex** [comment]
This is fine by me! I'm not going to get back to working on that PR until
next week.

I also think that if we're not able to remove the usage of AsPyPointer
entirely, marking it unsafe is a fine idea.

**Comment by davidhewitt** [comment]
As far as I'm currently thinking, I think once the following are reviewed / reworked / merged I will create a release PR:
- #3446
- #3455
- #3458

(All three close bugs which require small API adjustments to resolve.)
